; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:alt]
;platform = espressif32
;board = 4d_systems_esp32s3_gen4_r8n16
;framework = arduino
;lib_deps = TFT_eSPI, fbiego/ESP32Time@^2.0.6, electroniccats/MPU6050@^1.4.3
;monitor_filters = esp32_exception_decoder
;monitor_speed = 115200
;
;build_flags = 
;    -DBOARD_HAS_PSRAM
;    -mfix-esp32-psram-cache-issue
;    ; These ensure the N16R8 uses the fast Octal (OPI) mode
;    -DARDUINO_USB_CDC_ON_BOOT=1
;    -DDEV_UNIT
;    -DDEBUG

[env:alt]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Flash and PSRAM settings for 4MB Flash / 2MB PSRAM (Quad SPI)
board_upload.flash_size = 4MB
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio

; Required flag to enable PSRAM in code
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DDEV_UNIT
    
; Ensure partition table fits 4MB
board_build.partitions = default.csv
lib_deps = TFT_eSPI, fbiego/ESP32Time@^2.0.6, electroniccats/MPU6050@^1.4.3
