; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:s3-full]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_filters = esp32_exception_decoder
monitor_speed = 115200

lib_deps = 
    TFT_eSPI
    fbiego/ESP32Time@^2.0.6
    electroniccats/MPU6050@^1.4.3

board_build.arduino.psram = enabled
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.flash_mode = dio  
board_build.arduino.memory_type = dio_opi

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0  
    -DDEV_UNIT
    -DDISALLOW_SLEEP
    -DDEBUG

upload_port = COM8
monitor_port = COM8

[env:s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 4MB
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DDISALLOW_SLEEP
    -DDEV_UNIT
    
board_build.partitions = default.csv
lib_deps = TFT_eSPI, fbiego/ESP32Time@^2.0.6, electroniccats/MPU6050@^1.4.3
upload_port = COM5
monitor_port = COM5